version: "3.9"
services:
    react-app:
      image: react-app
      build: ./client/
      stdin_open: true
      ports: 
        - "3000:3000"
      networks: 
        - mern-app
      volumes: 
        - ./client/:/usr/app
        - /usr/app/node_modules
      environment: 
        - CHOKIDAR_USEPOLLING=true

    api-server:
      image: api-server
      build: ./server/
      ports: 
        - "5000:5000"
      networks: 
        - mern-app
      volumes: 
        - ./server/:/usr/app
        - /usr/app/node_modules

networks: 
  mern-app:
    driver: bridge

